name: Building and Pushed
on:
  schedule:
       - cron: "0 0 * * *"   
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - .github/workflows/main.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Determine tag
        run: | 
          cd /tmp
          git -c http.sslVerify=false clone https://github.com/drone/drone.git
          cd drone
          export TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          export TAG=${TAG:1}
          echo "::set-env name=TAG::$TAG"
          
      - name: Check $TAG
        run: echo $TAG
        
      - name: Build and push   
        uses: docker/build-push-action@v2
        with:
          path: . 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nemonik/drone
          tags: latest, ${{ env.TAG }}
